### ISSUE TITLE
Less maps are parsed as the wrong Node type

### ISSUE THREAD

**Issue by jwilsson** [shellscape/postcss-less#111]
_Originally filed at https://github.com/lesshint/lesshint/issues/492_

* Node Version: `10.10.0`
* NPM Version: `6.4.1`
* postcss-less Version: `2.0.0`

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
@var: {
    color: blue
};
```
This is apparently a new feature just released a few months ago (http://lesscss.org/features/#maps-feature).

### JavaScript

```js
const postcss= require('postcss');
const syntax = require('postcss-less');

const lessText = `@var: {
    color: blue
};`;

postcss([])
  .process(lessText, { syntax: syntax })
  .then(function (result) {
    console.log(result.root.first)
});

```

### Expected Behavior
To be parsed and returned as a `Declaration` node, like other variable assignments (e.g `@var: blue`). 

### Actual Behavior
It's parsed and returned as a `Rule` node.

### How can we reproduce the behavior?
Run the provided JS example.

**Comment by shellscape** [comment]
This one is tricky. With the work being done in #113, this will be parsed as a regular `AtRule` with the `name` property being `var:` - note the trailing colon. Differentiating between a regular at-rule and a map is going to be tricky, and I'm not sure we have to do that. Going to close for now. If it gets to be a pain on your end, let's revisit after v3.0.0 is out.

**Comment by jwilsson** [comment]
@shellscape Cool, I can probably work with that.
