### ISSUE TITLE
Can you link to the toolset the README talks about?

### ISSUE THREAD

**Issue by Pomax** [shellscape/postcss-less#116]
The readme says "For compiling LESS, please use the official toolset for LESS.", but I have no idea what that official toolset is, or where to find it. Can that become a link so people who were hoping to find the solution to just running `postcss -o main.css less/*.less` can get to a working setup quickly?

**Comment by shellscape** [comment]
http://lesscss.org/

**Comment by Pomax** [comment]
... in the readme? For someone who didn't write the readme, the fact that you mean "the less website" when you say "the official toolset" is definitely not obvious.
