### ISSUE TITLE
How to compile less mixins in postcss

### ISSUE THREAD

**Issue by minimit** [shellscape/postcss-less#148]
Sorry for asking here, but I don't find the solution anywere after many tries.

How can I make less mixins works in postcss? Is it possible? This plugin seems to export `@` rules.

I'd like to use postcss on my frontend library but I can't without the power of less mixins.

**Comment by shellscape** [comment]
This project is just a syntax for PostCSS which produces an AST for LESS. You'd have to work with the AST it produces to accomplish what you want to. We merged support for mixins in #65 in 2017.
