### ISSUE TITLE
TypeError: node.getIterator is not a function

### ISSUE THREAD

**Issue by LP1994** [shellscape/postcss-less#149]
node: 14.11.0;
npm: 6.14.8;
operating system: Windows 10;
postcss: 8.0.5;
postcss-less: 3.1.4;

Error description:
ERROR in ./src/styles/less/basic/Basic.less
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.getIterator is not a function
at LazyResult.visitTick (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss\lib\lazy-result.js:470:33)
at LazyResult.runAsync (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss\lib\lazy-result.js:357:30)
at async Object.loader (G:\SNWS\sn-micro-front-web-project-template\node_modules\postcss-loader\dist\index.js:94:14)
@ ./src/tplEJS/pages/AuditLogIndex.ejs (./node_modules/html-webpack-plugin/lib/loader.js!./src/tplEJS/pages/AuditLogIndex.ejs) 83:10-42

step:
When I use the following configuration, an error will be reported: TypeError: node.getIterator is not a function.
{
    test: /.less$/i,
    use: [
        {
            loader: 'file-loader',
            options: {
                name: '[name]_[sha512:contenthash:hex:6].css',
                outputPath: './styles/',
                emitFile: true,
                esModule: false,
            },
        },
        {
            loader: 'extract-loader',
        },
        {
            loader: 'css-loader',
            options: {
                url: true,
                import: true,
                importLoaders: 2,
                esModule: false,
            },
        },

        // If you comment out the "postcss-loader" below, you won't get an error(TypeError: node.getIterator is not a function).
        {
            loader: 'postcss-loader',
            options: {
                execute: false,
                sourceMap: false,
                postcssOptions: {
                    syntax: require( 'postcss-syntax' )( {
                        css: require( 'postcss-safe-parser' ),
                        sass: require( 'postcss-sass' ),
                        scss: require( 'postcss-scss' ),
                        less: require( 'postcss-less' ),
                    } ),
                },
            },
        },

        {
            loader: 'less-loader',
            options: {
                lessOptions: {
                    math: 'strict-legacy',
                    strictUnits: true,
                    noIeCompat: true,
                },
            },
        },
    ],
    sideEffects: true,
}

explain:
When processing ".less" files, if "postcss-loader" is not used, no error will be reported and it can be successfully compiled. If "postcss-loader" is used, an error will be reported. Moreover, the above configuration will not report an error in postcss 7. X, but it will be reported if it is updated to postcss 8. X.
I also submitted this question at "postcss"!!!

**Comment by LP1994** [comment]
I live in the East eight international time zone, so if you have any questions, you may not be able to reply in time. Please forgive me for the inconvenience.

**Comment by shellscape** [comment]
Please use the issue template for reporting a bug. Only then will I look into your issue.
