### ISSUE TITLE
PostCSS 8

### ISSUE THREAD

**Issue by ai** [shellscape/postcss-less#150]
* Node Version: 14.0
* NPM Version: 6.4
* postcss Version: 8
* postcss-less Version: 3.1.4

### LESS

N/A

### JavaScript

N/A

### Expected Behavior

`postcss-less` should have a major release with PostCSS 8 in dependencies to be able to generate PostCSS 8 AST.

[PostCSS 8 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0)

### Actual Behavior

`postcss-less` is still using PostCSS 7 and incompatible with PostCSS 8.

**Comment by shellscape** [comment]
👍 I'll take a look
