### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by yoyo837** [shellscape/postcss-less#152]
Called from stylelint:

![image](https://user-images.githubusercontent.com/6134547/99044806-4f107700-25cb-11eb-85dc-ae62c31ec528.png)

* Node Version: v12.19.0
* NPM Version: v6.14.8
* postcss Version: v7.0.35
* postcss-less Version: v3.1.4

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

### LESS

```less
.
```

### Expected Behavior

No crash

### Actual Behavior

Crashed

### How can we reproduce the behavior?
Create a new less file in vscode configured with `stylelint` plugin, and enter a dot to trigger the lint.

**Comment by shellscape** [comment]
Seems like an editor plugin or stylelint issue to me. That's not valid css or less.
