### ISSUE TITLE
Unknown word   CssSyntaxError with escaping js

### ISSUE THREAD

**Issue by stephenliu1944** [shellscape/postcss-less#153]
Node Version: v10.16.3
NPM Version: 6.9.0
postcss Version: 7.0.34
postcss-less Version: 3.1.4
stylelint Version: 10.1.0
LESS
```
// web/utils.less
@functions: ~`(function() {
        var fullWidth = 1920;
        var fullHeight = 1080;
        function convert(px, maxPx) {
            return (100 * px/maxPx).toFixed(5);
        }
        this.pxtovw = function(width) {
            return convert(width, fullWidth) + 'vw';
        }
        this.pxtovh = function(height) {
            return convert(height, fullHeight) + 'vh';
        }
})()`;
```
Errors
When running stylelint "web/utils.less"

web/utils.less
2:9  ✖  Unknown word   CssSyntaxError

Expected Behavior
No error.

Actual Behavior
Error.

How can we reproduce the behavior?
See above.

**Comment by shellscape** [comment]
Please provide a reasonable reproduction and I'll reopen the issue.
