### ISSUE TITLE
Update PostCSS to 8.4 and release in patch

### ISSUE THREAD

**Issue by ai** [shellscape/postcss-less#168]
Hi. We have a problem in Stylelint with broken PostCSS AST. Here is a deep investigation: https://github.com/stylelint/stylelint/issues/5766#issuecomment-1199268976

Long story short: it can be fixed if we will update `postcss` in `dependencies` to `^8.4.0`. Can you help us improve PostCSS ecosystem?

**Comment by JounQin** [comment]
postcss is peer dependency here, so I think there's no action to do here?

**Comment by ai** [comment]
Yes, you are right :-/

**Comment by shellscape** [comment]
Do let me know if you need anything else.
