### ISSUE TITLE
AtRule without body

### ISSUE THREAD

**Issue by shellscape** [shellscape/postcss-less#55]
Requesting a small improvement to the `AtRule` type. When parsing `@rule();` or `@rule;` it would be great to have a convenience property shared with regular `Rule` types; `node.ruleWithoutBody`. Presently we're having to frequently use:

`(node.type === 'atrule' && (!node.nodes || (node.nodes && node.nodes.length === 0)))`

which works, but it gets messy. Any chance of adding that property to `AtRule` nodes as well?

**Comment by shellscape** [comment]
@webschik is this project still being maintained? several issues nearly a month old haven't been responded to.

**Comment by webschik** [comment]
@shellscape, lately I didn't have free time to work on these issues :( I will try to find a time or take a day off to work a bit on this project. Also I would appreciate for any help and PR!

**Comment by shellscape** [comment]
Looks like this was added (https://github.com/shellscape/postcss-less/#rulerulewithoutbody) so closing :)
