### ISSUE TITLE
@import with option parsed incorrectly

### ISSUE THREAD

**Issue by shellscape** [shellscape/postcss-less#57]
Doesn't look like the parser is handling `@import` with options correctly. See http://lesscss.org/features/#import-options

Consider this import: `@import (inline) "foo.less";`

PostCSS-LESS parses and returns:

``` js
AtRule {
  raws: { before: '', between: '', afterName: ' ' },
  type: 'atrule',
  name: 'import',
  parent: 
   Root {
     raws: { semicolon: true, after: '' },
     type: 'root',
     nodes: [ [Circular] ],
     source: { input: [Object], start: [Object] },
     lastEach: 2,
     indexes: {} },
  source: 
   { start: { line: 1, column: 1 },
     input: Input { css: '@import (inline) "foo";', id: '<input css 1>' },
     end: { line: 1, column: 23 } },
  params: '(inline) "foo"',
  lastEach: 2,
  indexes: { '1': 0, '2': 0 } }
```

A few things wrong here. The `params` property contains the import option **and** the import file path. It would be a reasonable workaround if the parser was updated so that anything following the closing paren of params was treated as a separate value. However, imports could really benefit from having a separate node type to accommodate how LESS uses them.

**Comment by ccapndave** [comment]
A quick note - this breaks https://github.com/postcss/postcss-import, which expects `import` to be an `atrule`.

**Comment by shellscape** [comment]
@ccapndave they should probably consider using a different node type, as an import is not an atrule. the reason we added a custom one is for that reason. using atrule is a hackey,.
