### ISSUE TITLE
less mixins don't work

### ISSUE THREAD

**Issue by jakwuh** [shellscape/postcss-less#63]
Hi! I've tried an example from `Readme.md` and it doesn't work:
```js
import postCssLess from 'postcss-less';
const less = `
    .class2 {
        &:extend(.class1);
        .mixin-name(@param1, @param2);
    }
`;
const root = postCssLess.parse(less); // CssSyntaxError: <css input>:4:9: Unknown word
```

Seems like `postcss-less` doesn't support less mixins despite the description in `Readme.md`. Am I missing something?

Thanks in advance.

**Comment by RyKilleen** [comment]
I am also running into this issue. I'll be looking through the lib for away to contribute, if anyone can point me the right direction that might get me there quicker. 


Thanks a ton to @webschik for this by the way, it was exactly what I needed for a theme done in LESS.

**Comment by javidan** [comment]
Did you found solution for that? Have a same problem

**Comment by xnimorz** [comment]
fixed in https://github.com/webschik/postcss-less/pull/65

**Comment by shellscape** [comment]
#65 was merged. I'm going to close this for now, but if the issue resurfaces please post a comment.
