### ISSUE TITLE
Comment formatting breaking change but no major bump?

### ISSUE THREAD

**Issue by Siilwyn** [shellscape/postcss-less#67]
I am not sure about this but it looks like updating from `0.15` to `0.16` includes a breaking change to the comment formatting as printed in [these tests](https://travis-ci.org/Siilwyn/css-declaration-sorter-atom/jobs/229286835#L76).

**Comment by shellscape** [comment]
That was considered a bug fix since the source was being incorrectly modified. If your semver constraint was `^0.15.0` as per NPM default, then NPM shouldn't have pulled `0.16.0`, unless I'm bananas and it differs from semver (checked here http://jubianchi.github.io/semver-check/).

**Comment by Siilwyn** [comment]
Thank you for your reply I'll change my tests to match. Luckily npm it doesn't pull it in that's why there's a PR to increment it and thus discovered this change. :)

Even though it's a bug fix it's still a breaking change.

**Comment by shellscape** [comment]
Cool. I'll keep that in mind moving forward. With parsers like this it can be tricky.
