### ISSUE TITLE
Update to PostCSS 6.x

### ISSUE THREAD

**Issue by ntwb** [shellscape/postcss-less#85]
PostCSS 6.0.6 is the latest release.

I'd created a PR in #83 to test this, Travis CI passed all 3 jobs though this was not actually the case, when inspecting the job logs all 3 had failed but still returned an exit of `0`

_Apologies for deleting the template, but there was not much to answer with this issue context_

**Comment by shellscape** [comment]
Given the version it's on at present, that's probably bundled with a bunch of breaking changes. That's going to be a `major` version for this module for sure.

**Comment by marcusdarmstrong** [comment]
Would you be open to a contribution on this issue?

**Comment by shellscape** [comment]
@marcusdarmstrong surely.

**Comment by ai** [comment]
@shellscape we have PostCSS 7.0 right now. We really need to update parser, since most of the plugins support only 6-7 AST API.

If you have not time, write me, I will send people to help you.

**Comment by shellscape** [comment]
@ai happy to review PRs to update this

**Comment by ai** [comment]
@shellscape done https://github.com/shellscape/postcss-less/pull/112
