### ISSUE TITLE
Bracket selectors are considered mixin parameters.

### ISSUE THREAD

**Issue by HauptmannEck** [shellscape/postcss-less#96]
* Node Version: v6.10.3
* NPM Version: v5.5.1
* postcss-less Version: v1.1.3

### LESS

```less
.a,
.b[type=text] {
  color: blue;
}
```

### JavaScript

```js
let postCssLess = require('./dist/less-syntax');
const less = `
.a,
.b[type=text] {
  color: blue;
}
`;
const root = postCssLess.parse(less);
console.log(root);
```

### Expected Behavior
No `params` set to match other postcss outputs.

### Actual Behavior
Bracket selector is considered a `params` value.

### How can we reproduce the behavior?
Use above JS file at project root.
This issue was found when using `stylelint`.

**Comment by shellscape** [comment]
Thanks for the issue! We'd be happy to review a Pull Request to fix this one!

**Comment by HauptmannEck** [comment]
@shellscape Thanks for verifying and merging that change. When will a new release be cut to implement this change? I will be able to fix a bug in stylelint with the new version.

**Comment by catearcher** [comment]
> When will a new release be cut to implement this change?

Wondering the same thing. We have been waiting for months for this fix and would love to update.

**Comment by shellscape** [comment]
@catearcher considering the patch only landed two weeks and change ago, I'd challenge that assessment. if it'd been a month or so since the commit then a ping would've been warranted, but otherwise exercise some patience - this isn't a full-time job.

**Comment by catearcher** [comment]
@shellscape Sorry, I meant no disrespect; the months I was referring to was since this was discovered in stylelint/stylelint#2791 in August 2017. I guess we can wait a little longer. :)
